FROM python:3.7

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libudev-dev \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libswscale-dev \
        libswresample-dev \
        libavfilter-dev \
        git \
      openssh-server \
      rsync \
      sudo \
      tmux \
      vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

# Setup hass-release
RUN git clone --depth 1 https://github.com/home-assistant/hass-release \
    && cd hass-release \
    && pip3 install -e .

WORKDIR /workspaces

# Install Python dependencies from requirements
COPY requirements_test.txt requirements_test_pre_commit.txt homeassistant/package_constraints.txt ./
RUN pip3 install -r requirements_test.txt -c package_constraints.txt \
    && rm -f requirements_test.txt package_constraints.txt requirements_test_pre_commit.txt

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash

RUN mkdir ~/.ssh && chmod 700 ~/.ssh
COPY docker/authorized_keys /root/.ssh/authorized_keys
COPY docker/.gitconfig /root/.gitconfig
RUN chmod 600 ~/.ssh/authorized_keys
RUN echo service ssh start >> /etc/bash.bashrc

